// Generated by `uvmstudio ci jenkins`.
pipeline {
  agent any
  options {
    timeout(time: 2, unit: 'HOURS')
    disableConcurrentBuilds()
  }
  parameters {
    choice(name: 'TIER', choices: ['L0','L1','L2','L3','L4','L5'],
           description: 'Regression tier')
    string(name: 'SEED', defaultValue: '1', description: 'Base seed')
    string(name: 'JOBS', defaultValue: '4', description: 'Parallel jobs')
  }
  environment {
    UVM_HOME = "${WORKSPACE}/third_party/uvm-core/src"
  }
  stages {
    stage('Setup') {
      steps {
        sh 'python3 -m pip install --user -e .'
        sh 'test -d third_party/uvm-core || git clone --depth 1 https://github.com/accellera-official/uvm-core.git third_party/uvm-core'
        sh 'uvmstudio env --json > toolchain.json'
      }
    }
    stage('Compile') {
      steps { sh 'uvmstudio compile -p examples/golden_apb --json > compile.json' }
    }
    stage('Lint') {
      steps { sh 'uvmstudio lint -p examples/golden_apb --json > lint.json || true' }
    }
    stage('Regress') {
      steps {
        sh 'uvmstudio regress -p examples/golden_apb --tier ${params.TIER} --seed ${params.SEED} -j ${params.JOBS}'
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: '**/results/**/report.*, **/results/**/repro.json, **/results/**/sim.log, *.json',
                       allowEmptyArchive: true
      publishHTML(target: [reportDir: 'examples/golden_apb/results', reportFiles: '**/report.html',
                           reportName: 'Regression Report', keepAll: true])
    }
  }
}
