#!/usr/bin/env bash
# Generated by `uvmstudio ci cli`. Portable entry point for any CI system.
set -euo pipefail

PROJ="${1:-examples/golden_apb}"
TIER="${2:-L2}"
SEED="${3:-1}"
JOBS="${4:-2}"

echo "== toolchain =="
uvmstudio env

echo "== compile =="
uvmstudio compile -p "$PROJ"

echo "== lint =="
uvmstudio lint -p "$PROJ" || echo "lint findings present (non-blocking)"

echo "== regress =="
uvmstudio regress -p "$PROJ" --tier "$TIER" --seed "$SEED" -j "$JOBS"
