<#
 .SYNOPSIS
   UVM Verification Studio driver for Windows PowerShell.
 .DESCRIPTION
   Generated by `uvmstudio ci cli`. Runs the same commands as the POSIX
   entry point. On Windows the simulator backend dispatches into WSL
   automatically; pass -ExecHost to force it.
 .EXAMPLE
   .\uvmstudio-ci.ps1 -Project . -Tier L1 -Seed 1 -Jobs 4
#>
[CmdletBinding()]
param(
  [string]$Project  = "examples/golden_apb",
  [ValidateSet('L0','L1','L2','L3','L4','L5')]
  [string]$Tier     = "L2",
  [int]   $Seed     = 1,
  [int]   $Jobs     = 2,
  [ValidateSet('native','wsl','remote')]
  [string]$ExecHost,
  [string]$WslDistro
)

$ErrorActionPreference = 'Stop'

$backendArgs = @()
if ($ExecHost)  { $backendArgs += @('--exec-host', $ExecHost) }
if ($WslDistro) { $backendArgs += @('--wsl-distro', $WslDistro) }

function Invoke-Studio {
  param([string[]]$StudioArgs, [switch]$AllowFailure)
  Write-Host "> uvmstudio $($StudioArgs -join ' ')" -ForegroundColor Cyan
  & uvmstudio @StudioArgs
  if ($LASTEXITCODE -ne 0 -and -not $AllowFailure) {
    throw "uvmstudio $($StudioArgs -join ' ') failed with exit code $LASTEXITCODE"
  }
  return $LASTEXITCODE
}

Write-Host '== toolchain ==' -ForegroundColor Yellow
Invoke-Studio @('env')

Write-Host '== compile ==' -ForegroundColor Yellow
Invoke-Studio @('compile', '-p', $Project)

Write-Host '== lint ==' -ForegroundColor Yellow
Invoke-Studio @('lint', '-p', $Project) -AllowFailure | Out-Null

Write-Host '== regress ==' -ForegroundColor Yellow
$rc = Invoke-Studio (@('regress', '-p', $Project, '--tier', $Tier,
                       '--seed', $Seed, '-j', $Jobs) + $backendArgs) -AllowFailure

if ($rc -eq 0) {
  Write-Host 'STATUS: PASS' -ForegroundColor Green
} else {
  Write-Host "STATUS: NOT PASSED (exit $rc)" -ForegroundColor Red
}
exit $rc
