"""CI pipeline generation.

The platform does not replace GitHub Actions, GitLab CI or Jenkins — it emits
pipelines that call the `uvmstudio` CLI. That keeps the CI definition thin and
means a pipeline can never drift from what runs locally: both go through the
same commands.
"""

from __future__ import annotations

from pathlib import Path

from ..core.project import Project

_GITHUB = """\
# Generated by `uvmstudio ci github`. Safe to edit; regenerate to reset.
name: {name} verification

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:
    inputs:
      tier:
        description: Regression tier
        default: '{tier}'
        type: choice
        options: [L0, L1, L2, L3, L4, L5]

concurrency:
  group: ${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

env:
  UVM_HOME: ${{{{ github.workspace }}}}/third_party/uvm-core/src

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # reproducibility metadata needs real git state

      - name: Install toolchain
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \\
            verilator z3 git build-essential
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .

      - name: Fetch Accellera UVM
        run: |
          mkdir -p third_party
          git clone --depth 1 https://github.com/accellera-official/uvm-core.git \\
            third_party/uvm-core

      - name: Toolchain report
        run: uvmstudio env --json | tee toolchain.json

      - name: Compile / elaborate
        run: uvmstudio compile -p {proj} --json | tee compile.json

      - name: Lint
        run: uvmstudio lint -p {proj} --json | tee lint.json
        continue-on-error: true

      - name: Regression
        run: |
          uvmstudio regress -p {proj} \\
            --tier "${{{{ github.event.inputs.tier || '{tier}' }}}}" \\
            --seed 1 -j 2

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verification-results
          path: |
            toolchain.json
            compile.json
            lint.json
            {proj}/results/**/report.*
            {proj}/results/**/repro.json
            {proj}/results/**/sim.log
            {proj}/results/**/*.fst
            {proj}/results/**/*.vcd
          retention-days: 30
"""

_GITLAB = """\
# Generated by `uvmstudio ci gitlab`.
stages: [setup, compile, regress]

variables:
  UVM_HOME: "$CI_PROJECT_DIR/third_party/uvm-core/src"
  GIT_DEPTH: "0"
  TIER: "{tier}"

default:
  image: ubuntu:24.04
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends verilator z3 git python3-pip build-essential
    - pip3 install --break-system-packages -e .
    - test -d third_party/uvm-core || git clone --depth 1 https://github.com/accellera-official/uvm-core.git third_party/uvm-core

toolchain:
  stage: setup
  script:
    - uvmstudio env --json | tee toolchain.json
  artifacts:
    paths: [toolchain.json]

compile:
  stage: compile
  script:
    - uvmstudio compile -p {proj} --json | tee compile.json
    - uvmstudio lint -p {proj} --json | tee lint.json || true
  artifacts:
    paths: [compile.json, lint.json]
    when: always

regress:
  stage: regress
  script:
    - uvmstudio regress -p {proj} --tier "$TIER" --seed 1 -j 2
  artifacts:
    when: always
    paths:
      - {proj}/results/
    reports:
      junit: {proj}/results/junit.xml
"""

_JENKINS = """\
// Generated by `uvmstudio ci jenkins`.
pipeline {{
  agent any
  options {{
    timeout(time: 2, unit: 'HOURS')
    disableConcurrentBuilds()
  }}
  parameters {{
    choice(name: 'TIER', choices: ['L0','L1','L2','L3','L4','L5'],
           description: 'Regression tier')
    string(name: 'SEED', defaultValue: '1', description: 'Base seed')
    string(name: 'JOBS', defaultValue: '4', description: 'Parallel jobs')
  }}
  environment {{
    UVM_HOME = "${{WORKSPACE}}/third_party/uvm-core/src"
  }}
  stages {{
    stage('Setup') {{
      steps {{
        sh 'python3 -m pip install --user -e .'
        sh 'test -d third_party/uvm-core || git clone --depth 1 https://github.com/accellera-official/uvm-core.git third_party/uvm-core'
        sh 'uvmstudio env --json > toolchain.json'
      }}
    }}
    stage('Compile') {{
      steps {{ sh 'uvmstudio compile -p {proj} --json > compile.json' }}
    }}
    stage('Lint') {{
      steps {{ sh 'uvmstudio lint -p {proj} --json > lint.json || true' }}
    }}
    stage('Regress') {{
      steps {{
        sh 'uvmstudio regress -p {proj} --tier ${{params.TIER}} --seed ${{params.SEED}} -j ${{params.JOBS}}'
      }}
    }}
  }}
  post {{
    always {{
      archiveArtifacts artifacts: '**/results/**/report.*, **/results/**/repro.json, **/results/**/sim.log, *.json',
                       allowEmptyArchive: true
      publishHTML(target: [reportDir: '{proj}/results', reportFiles: '**/report.html',
                           reportName: 'Regression Report', keepAll: true])
    }}
  }}
}}
"""

_SH = """\
#!/usr/bin/env bash
# Generated by `uvmstudio ci cli`. Portable entry point for any CI system.
set -euo pipefail

PROJ="${{1:-{proj}}}"
TIER="${{2:-{tier}}}"
SEED="${{3:-1}}"
JOBS="${{4:-2}}"

echo "== toolchain =="
uvmstudio env

echo "== compile =="
uvmstudio compile -p "$PROJ"

echo "== lint =="
uvmstudio lint -p "$PROJ" || echo "lint findings present (non-blocking)"

echo "== regress =="
uvmstudio regress -p "$PROJ" --tier "$TIER" --seed "$SEED" -j "$JOBS"
"""

_PS1 = """\
<#
 .SYNOPSIS
   UVM Verification Studio driver for Windows PowerShell.
 .DESCRIPTION
   Generated by `uvmstudio ci cli`. Runs the same commands as the POSIX
   entry point. On Windows the simulator backend dispatches into WSL
   automatically; pass -ExecHost to force it.
 .EXAMPLE
   .\\uvmstudio-ci.ps1 -Project . -Tier L1 -Seed 1 -Jobs 4
#>
[CmdletBinding()]
param(
  [string]$Project  = "{proj}",
  [ValidateSet('L0','L1','L2','L3','L4','L5')]
  [string]$Tier     = "{tier}",
  [int]   $Seed     = 1,
  [int]   $Jobs     = 2,
  [ValidateSet('native','wsl','remote')]
  [string]$ExecHost,
  [string]$WslDistro
)

$ErrorActionPreference = 'Stop'

$backendArgs = @()
if ($ExecHost)  {{ $backendArgs += @('--exec-host', $ExecHost) }}
if ($WslDistro) {{ $backendArgs += @('--wsl-distro', $WslDistro) }}

function Invoke-Studio {{
  param([string[]]$StudioArgs, [switch]$AllowFailure)
  Write-Host "> uvmstudio $($StudioArgs -join ' ')" -ForegroundColor Cyan
  & uvmstudio @StudioArgs
  if ($LASTEXITCODE -ne 0 -and -not $AllowFailure) {{
    throw "uvmstudio $($StudioArgs -join ' ') failed with exit code $LASTEXITCODE"
  }}
  return $LASTEXITCODE
}}

Write-Host '== toolchain ==' -ForegroundColor Yellow
Invoke-Studio @('env')

Write-Host '== compile ==' -ForegroundColor Yellow
Invoke-Studio @('compile', '-p', $Project)

Write-Host '== lint ==' -ForegroundColor Yellow
Invoke-Studio @('lint', '-p', $Project) -AllowFailure | Out-Null

Write-Host '== regress ==' -ForegroundColor Yellow
$rc = Invoke-Studio (@('regress', '-p', $Project, '--tier', $Tier,
                       '--seed', $Seed, '-j', $Jobs) + $backendArgs) -AllowFailure

if ($rc -eq 0) {{
  Write-Host 'STATUS: PASS' -ForegroundColor Green
}} else {{
  Write-Host "STATUS: NOT PASSED (exit $rc)" -ForegroundColor Red
}}
exit $rc
"""


def generate(project: Project, system: str, out_dir: Path) -> list[Path]:
    """Write CI files for `system` into `out_dir`. Returns the paths written."""
    proj_rel = _relative(project.root, out_dir)
    tier = _highest_tier(project)
    written: list[Path] = []

    def w(rel: str, text: str, *, executable: bool = False) -> None:
        p = out_dir / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
        if executable:
            p.chmod(0o755)
        written.append(p)

    fmt = {"name": project.name, "proj": proj_rel, "tier": tier}

    if system == "github":
        w(".github/workflows/verification.yml", _GITHUB.format(**fmt))
    elif system == "gitlab":
        w(".gitlab-ci.yml", _GITLAB.format(**fmt))
    elif system == "jenkins":
        w("Jenkinsfile", _JENKINS.format(**fmt))
    elif system == "cli":
        w("uvmstudio-ci.sh", _SH.format(**fmt), executable=True)
        w("uvmstudio-ci.ps1", _PS1.format(**fmt))
    else:
        raise ValueError(f"unknown CI system {system!r}")
    return written


def _relative(project_root: Path, out_dir: Path) -> str:
    try:
        rel = project_root.resolve().relative_to(out_dir.resolve())
        return str(rel) if str(rel) != "." else "."
    except ValueError:
        return str(project_root)


def _highest_tier(project: Project) -> str:
    order = ["L0", "L1", "L2", "L3", "L4", "L5"]
    tiers = {t.tier for t in project.tests if t.tier in order}
    return max(tiers, key=order.index) if tiers else "L1"
